<?php
require('fpdf/fpdf.php');

// Koneksi ke database
$conn = new mysqli("localhost", "root", "", "gusti");
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Ambil data berdasarkan filter tanggal (jika ada)
$start_date = isset($_GET['start_date']) ? $_GET['start_date'] : '';
$end_date = isset($_GET['end_date']) ? $_GET['end_date'] : '';

$sql = "SELECT * FROM firdaus";
if (!empty($start_date) && !empty($end_date)) {
    $sql .= " WHERE tanggal_input BETWEEN '$start_date' AND '$end_date' ORDER BY tanggal_input ASC";
}

$result = $conn->query($sql);

// Inisialisasi PDF
$pdf = new FPDF('P', 'mm', 'A4');
$pdf->AddPage();
$pdf->SetMargins(10, 10, 10);  // Set margin agar lebih rapi
$pdf->SetFont('Arial', 'B', 14);

// Judul Laporan
$pdf->Cell(0, 10, 'Laporan Data Mahasiswa', 0, 1, 'C');
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(0, 10, 'Tanggal Laporan: ' . date('d-m-Y'), 0, 1, 'C');
$pdf->Ln(5);  // Spasi kosong

// Header Tabel dengan Background
$pdf->SetFillColor(0, 123, 255);  // Warna biru untuk header
$pdf->SetTextColor(255, 255, 255);  // Teks putih
$pdf->SetFont('Arial', 'B', 10);

// Lebar kolom disesuaikan untuk menjaga layout
$col_widths = [
    'nim' => 25,
    'gambar' => 25,
    'nama' => 55,
    'fakultas' => 40,
    'tanggal_input' => 35
];

// Header tabel
$pdf->Cell($col_widths['nim'], 8, 'NIM', 1, 0, 'C', true);
$pdf->Cell($col_widths['gambar'], 8, 'Gambar', 1, 0, 'C', true);
$pdf->Cell($col_widths['nama'], 8, 'Nama', 1, 0, 'C', true);
$pdf->Cell($col_widths['fakultas'], 8, 'Fakultas', 1, 0, 'C', true);
$pdf->Cell($col_widths['tanggal_input'], 8, 'Tanggal Input', 1, 1, 'C', true);

// Reset Warna untuk Isi Tabel
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('Arial', '', 10);

// Fungsi untuk menulis teks dengan MultiCell dan tetap menggambar garis
function writeCellWithBorder($pdf, $width, $height, $text) {
    $x = $pdf->GetX();  // Simpan posisi X
    $y = $pdf->GetY();  // Simpan posisi Y

    // Tulis teks dengan MultiCell (bungkus teks panjang)
    $pdf->MultiCell($width, 6, $text, 0, 'L');

    // Gambarkan garis kotak manual di sekitar sel
    $pdf->Rect($x, $y, $width, $height);

    // Kembalikan posisi ke awal agar tetap sejajar dengan sel berikutnya
    $pdf->SetXY($x + $width, $y);
}

// Isi Data
while ($row = $result->fetch_assoc()) {
    // NIM
    $pdf->Cell($col_widths['nim'], 25, $row['NIM'], 1, 0, 'C');

    // Gambar
    if (!empty($row['gambar']) && file_exists("uploads/" . $row['gambar'])) {
        $pdf->Cell($col_widths['gambar'], 25, '', 1, 0);  // Kotak untuk gambar
        // Sesuaikan ukuran gambar menjadi lebih kecil, misalnya 15x15 mm
        $pdf->Image("uploads/" . $row['gambar'], $pdf->GetX() - $col_widths['gambar'] + 5, $pdf->GetY() + 5, 15, 15);
    } else {
        $pdf->Cell($col_widths['gambar'], 25, 'Tidak Ada Gambar', 1, 0, 'C');
    }

    // Nama (gunakan fungsi MultiCell dengan border)
    writeCellWithBorder($pdf, $col_widths['nama'], 25, $row['NAMA']);

    // Fakultas (gunakan fungsi MultiCell dengan border)
    writeCellWithBorder($pdf, $col_widths['fakultas'], 25, $row['FAKULTAS']);

    // Tanggal Input
    $pdf->Cell($col_widths['tanggal_input'], 25, date('d-m-Y', strtotime($row['tanggal_input'])), 1, 1, 'C');
}

// Footer
$pdf->Ln(10);
$pdf->SetFont('Arial', 'I', 10);
$pdf->Cell(0, 10, 'Generated by Sistem Mahasiswa - ' . date('d-m-Y H:i:s'), 0, 0, 'L');

// Output PDF
$pdf->Output();

// Tutup koneksi database
$conn->close();
?>
